export const uiSelectorsConf: IUiSelectorsConf[] = [
  {
    path: "/dashboard",
    tsType: "period",
    mpsType: "multiple",
    ssType: "multiple",
  },
  {
    path: "/mysales/sales",
    tsType: "period",
    mpsType: "mono",
    ssType: "multiple",
  },
  {
    path: "/mysales/brands",
    tsType: "period",
    mpsType: "mono",
    ssType: "multiple",
  },
  {
    path: "/mysales/goods",
    tsType: "period",
    mpsType: "mono",
    ssType: "multiple",
  },
  {
    path: "/mysales/sales_dynamics",
    tsType: "week",
    mpsType: "mono",
    ssType: "multiple",
  },
  {
    path: "/mysales/sales_geography",
    tsType: "period",
    mpsType: "mono",
    ssType: "multiple",
  },
  {
    path: "/mygoods/goods",
    tsType: "period",
    mpsType: "mono",
    ssType: "multiple",
  },
  {
    path: "/mygoods/new_card",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/mygoods/templates",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/product/:id",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/scanner",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/autorestorer",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/telegram_bots",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/mp_connect",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/darkside/complaints",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/profile/user",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/profile/payments",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/profile/security",
    tsType: null,
    mpsType: null,
    ssType: null,
  },
  {
    path: "/live/timeline",
    tsType: null,
    mpsType: "multiple",
    ssType: null,
  },
  {
    path: "/live/orders",
    tsType: null,
    mpsType: "multiple",
    ssType: null,
  },
];
