type INewCardFormFields = {
  barcode: string;
  brand: string;
  country: string;
  depth: string;
  description?: string;
  height: string;
  old_price?: string;
  premium_price?: string;
  price: string;
  weight: string;
  width: string;
  shops: ISelectShopField[];
  title: string;
  price: string;
  oz_category?: ICategoryOzRes | null;
  wb_category?: ICategoryRes | null;
  ym_category?: string[];
  images: Files[];
  videos: Files[];
  stereos: Files[];
  vat: TVat;
  oz?: Record<string, ISpecsOzRes | ISpecsOzRes[] | string | undefined>;
  ym?: Record<string, number>;
  certificate?: string;
  vendor?: string;
  vendorCode?: string;
  boxCount?: string;
};
